### ISSUE TITLE
Profile editor disappear for 372.54

### ISSUE THREAD

**Issue by Explorare** [Orbmu2k/nvidiaProfileInspector#10]
The profile editor icon disappear for 372.54 WHQL.
How to fix this?

**Comment by DeadManWalkingTO** [comment]
[DeadManWalkingTO/NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)
forked from [Orbmu2k/nvidiaProfileInspector](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)

Release Binaries (New Versions - Updates)
