### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by Klemci** [Orbmu2k/nvidiaProfileInspector#102]
Well, a branch linked on [PCGWiki](https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector) just been 404'ed (now invisible) a few minutes after somebody answered to my long time post...

... so, may i ask if the "Nathan Binks AKA FoulPlay" fork is not recommended at all afterall ?

**Possible reason !?! :**
`I am not a software developer. I am a 27 year old Autistic fellow that dabbles with code. And currently very ill to carry on with projects.
`

**Comment by FoulPlay** [comment]
Hi, I'm in and out of hospital with Psychosis. It's a severe mental disorder in which thought, and emotions are so impaired that contact is lost with external reality.

I'm struggling with it that I got fed up with working on it until' I get MS's Visual Studio set up. 

I am swapping IDE's for working on it and with that illness, I get fed up easily and tend to do other stuff to calm down.

I am working on it again and pulling a request to the latest NvAPI which I have access to. R515.

Sorry. I am back on working on this.

**Comment by FoulPlay** [comment]
Done. Latest R515 and Framework 4.8.1 is now used.

**Comment by couleurm** [comment]
> Done. Latest R515 and Framework 4.8.1 is now used.

where was this released/from?

**Comment by Klemci** [comment]
If the APIs updates can help you, that's good, thanks, i'll take a look to update.

@couleurm : look on [PCGWiki ("officilay" back; ) )](https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector)

**Comment by Klemci** [comment]
OKay, mouse wheel works fully now, fixed !!
