### ISSUE TITLE
forcing rebar/smartbar

### ISSUE THREAD

**Issue by d0x360** [Orbmu2k/nvidiaProfileInspector#103]
Hopefully nvidia moves to a blacklist soon but i just wanted to double check something...

In the older version of profile inspector you had to change 3 flags to enable it assuming all hardware supported it.  In this there are only 2 flags.

Was the 3rd made unnecessary?

Thanks

**Comment by aufkrawall** [comment]
Perhaps you just overlooked it? There are still 
0X000F00BA
0X000F00BB
0X000F00FF

No clue about Nvidia's plans for a blacklist, but in case this is not what they have in mind, I think it would be neat to have these options visible and labeled under e.g. "Common" section.
