### ISSUE TITLE
Search for app in the Store

### ISSUE THREAD

**Issue by jerryc05** [Orbmu2k/nvidiaProfileInspector#105]
Win11, just downloaded and double clicked to open, but I got this prompt which blocked me from using it.

![image](https://user-images.githubusercontent.com/8305074/201544196-f37aa532-f115-4fcf-b20a-807ca338c3bf.png)

Choosing YES brings me to MS Store but shows nothing found.

![image](https://user-images.githubusercontent.com/8305074/201544239-6a94db46-1d1e-41df-81dc-1ecf3b151d2e.png)

**Comment by jerryc05** [comment]
v2.4.0.1

**Comment by Evernow** [comment]
Can you right click the file you're trying to open that creates that prompt then go to properties and take a screenshot?

**Comment by jerryc05** [comment]
> Can you right click the file you're trying to open that creates that prompt then go to properties and take a screenshot?

That inspired me. I checked the unlock checkbox in properties tab and then everything went fine. thx
