### ISSUE TITLE
StereoProfile

### ISSUE THREAD

**Issue by speed-of-heat** [Orbmu2k/nvidiaProfileInspector#106]
StereoProfile 
this seems to have gone from the latest couple of releases is it still in use or did it get replaced with something? or is it an oversight?  It was present in 2.3.13 and earlier.

**Comment by Orbmu2k** [comment]
Stereo has been removed. 3D Vision is not supported anymore by the driver for ages now.
https://nvidia.custhelp.com/app/answers/detail/a_id/4781

if you still using old 3dvision rigs with older drivers you should also stay on old profile inspector ;-)

**Comment by speed-of-heat** [comment]
Understood thanks

Thanks,
Stuart

Get Outlook<https://aka.ms/sdimjr> for iOS
________________________________
