### ISSUE TITLE
its not letting me open the program, i run it as administrator and normally. it doesn't open and idk why pls help.

### ISSUE THREAD

**Issue by ghoostzz** [Orbmu2k/nvidiaProfileInspector#107]

**Comment by Aldin101** [comment]
Please note that GitHub issues is the a great place to ask for help but I will give a likely fix anyways

right click the program
press properties 
then at the bottom of that menu check the box next to "unblock"
then press OK to apply your changes and close the window. 
then right click the program and press run as administrator and then accept the user account control prompt.
