### ISSUE TITLE
Nvidia Inspector - version 1.9.7.3

### ISSUE THREAD

**Issue by ramonsantana** [Orbmu2k/nvidiaProfileInspector#108]
Can you check the code on Nvidia Inspector - version 1.9.7.3
Trying to disable VSync but even if I cap fps at 60 the screen tears.
Any other version of Nvidia Inspector does not cap the frame rate at a perfect and stable 16.7ms. Thus, if you play at 60hz, as I do, it is crucial to hit a precise 16.7ms response time on your GPU in order to match the refresh rate of a 60Hz monitor, subsequently eliminating any noticeable screen tear.

**Comment by Orbmu2k** [comment]
Framelimiter V3 @ 58FPS + Ultra Low Latency = ON schould eleminate every tearing with perfect input lag
