### ISSUE TITLE
Version 2.1.3.2 Is crashing Windows Graphics Drivers 

### ISSUE THREAD

**Issue by Rinsewood** [Orbmu2k/nvidiaProfileInspector#11]
When i set the Sli compability bits for rFactor 2 i the 372.90 drivers, it works fine til i restart the computer, after that rFactor2  gets WERY sluggish, displays about 8 frames of gameplay, and i have to reinstall the drivers and set the sli bits again, when i do that the game works fine, UNTIL i restart the comp, then its all fucked up again. Reinstall the GPU drivers and redo the procedure.

Something that can be due to the new Profile inspector or something else.

**Comment by Orbmu2k** [comment]
probably a driver / game issue, not inspector related, try older drivers
