### ISSUE TITLE
"Restore profile to Nvidia defaults" problem

### ISSUE THREAD

**Issue by ShodanCat** [Orbmu2k/nvidiaProfileInspector#110]
The "Restore profile to Nvidia defaults"  button does not restore the two ULL entries

**Comment by Orbmu2k** [comment]
not reproduceable for me, works just fine

**Comment by ShodanCat** [comment]
> not reproduceable for me, works just fine

try making a profile from scratch for some .exe. the reset to global defaults will reset the ULL settings on an "original" profile but not the user-created one

**Comment by Orbmu2k** [comment]
should be fixed in https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.4.0.4

**Comment by charlie2231** [comment]
I accidentally deleted the Fortnite file from the NVIDIA Profile Inspector plss help

**Comment by BLXXSD** [comment]
I deleted fortnite off of it can you help me fix this ????
