### ISSUE TITLE
Resizable Bar

### ISSUE THREAD

**Issue by FabToGo** [Orbmu2k/nvidiaProfileInspector#111]
I'm a bit worried. The newest version (2.4.0.3) lacks the 0x000FF00BF, 0x000FF00BB and 0x000FF00FF. How come?

**Comment by d0x360** [comment]
i asked the same a few weeks ago and he said they were there but i couldnt findd all 3...

im using version 2.3.0.13  which has more options inlcuding the 3 flags needed.

Did nvidia change them or something?  I know they still work via whitelist and most games arent whitelsted.

Spiderman wasnt and when  enabled it it performed much better for me....

Any clarification would be fantastic

**Comment by FabToGo** [comment]
Thx for your answer!

**Comment by d0x360** [comment]
Nevermind, now I feel stupid lol.

It's been moved from unknown and it's actually had a green dot put next to
it so it sticks out.

Just looking in the wrong place.  Sorry bout that

**Comment by d0x360** [comment]
Nevermind, now I feel stupid lol.

It's been moved from unknown and it's actually had a green dot put next to
it so it sticks out.

Just looking in the wrong place.  Sorry bout that

*Now with pictures!  Well just 1

![pinspect](https://user-images.githubusercontent.com/14056857/204408644-fd495a0e-57f7-49e3-b818-2e6d10bda21c.jpg)
