### ISSUE TITLE
Commandline to change settings? [Feature Request]

### ISSUE THREAD

**Issue by CaptainXLAB** [Orbmu2k/nvidiaProfileInspector#112]
I specifically use profile inspector to disable "CUDA - Force P2 State" since I use XOC BIOS with a 2080Ti which only has P0 and P8 states and when P2 state is forced, it switches to P8 state which makes everything crippling and slow.

Everytime a driver update is done, this setting resets. If I manually change to a different driver, then also this setting resets.

It will be very very nice to have a simple CLI option to run the same exe and pass a few arguments that apply/save changes. Then I can use anything like CRU's "restart.exe" tool to restart display driver and make the changes take effect = one-click batch file solution to set things up. Will also be nice to be able to load profiles/etc from CLI too, it'll be very useful to set stuff up on fresh installs with one click.

Thanks!

**Comment by Orbmu2k** [comment]
you can export the profile as NIP, and refine/edit the xml to your needs

this NIP can be executed with Profile Inspector to import the setting(s)

**Comment by CaptainXLAB** [comment]
With CLI, I managed to do it like this - wrote this in a batch file (.bat)
`"C:\Program Files\NVidiaProfileInspectorDmW\NVidiaProfileInspectorDmW.exe" "C:\Scripts\DriverControl\Base Profile.nip"`
Just need to `taskkill /f /im nvidiaprofileinspectordmw.exe` since it creates a confirmation dialog box after it restores the profile.

Ended up working perfectly, effortless driver updates and reinstalls :D
Thanks!

**Comment by CaptainXLAB** [comment]
> just use the "-silent" parameter ;-)

Perfect...!

> BTW you are using a DmW fork version, but reporting issue here on the main fork?

Oh, my bad, didn't know these are different versions... I quickly downloaded the first thing I saw 2 years ago in a rush and I was still using that. Had no idea what "dmw" meant or what it did differently.

On a quick google search for `nvidia profile inspector`, it shows some website named `nvidiaprofileinspector.com` which has the title `Download Nvidia Profile Inspector 3.5.0.0 Latest Version` which links to the dmw version, but if I search for `profile inspector nvidia` then the first result is this github. Strange and was very easy to mistake dmw version for the only main version.

Switched back to the main version now since it's updated more frequently :D
Thanks for pointing that out too!
