### ISSUE TITLE
Feature request: saved profile load from command line

### ISSUE THREAD

**Issue by T-Troll** [Orbmu2k/nvidiaProfileInspector#113]
It's a bunch of situations profile settings (especially default one) should be massively altered with some situation.
For example, it's useful to do it for Optimus systems for different situations.

For now, you should open control panel and change it manually, or, much better, open Profile Inspector and use a saved profile with pre-defined settings.

But it needs to be done by manual clicks anyway.

Is it a way to add command-line support to automatically update profile? This give a possibility for automatization of this switch (by scheduler/macro/script etc.)?

**Comment by Orbmu2k** [comment]
You can use settings import for that, see #112 

If you like to change specific settings for ALL profiles, just use global settings as its designed for this. :)

**Comment by T-Troll** [comment]
Danke schoen!
