### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Retr0680** [Orbmu2k/nvidiaProfileInspector#114]
getting this error whenever trying to open it

![image](https://user-images.githubusercontent.com/82796288/206358038-0ab42db5-ace9-4b63-af4d-0afb1334f6c3.png)

**Comment by bibarub** [comment]
same. windows 8.1, geforce 410m, driver 391.35

**Comment by Orbmu2k** [comment]
keep the last working version, if you keep old drivers ;-)
