### ISSUE TITLE
Nvidia Inspector?

### ISSUE THREAD

**Issue by toiletpotato** [Orbmu2k/nvidiaProfileInspector#124]
Does Nvidia Inspector exist anymore?  Or is it only Nvidia Profile Inspector now, because I can't seem to find a standalone download for Inspector, except for one that is years old, or one that is bloated with malware?  If someone can fill me in or point me in the right direction I would appreciate it, thanks.

I guess even the last source version of Inspector would be fine, I could use a short project.

**Comment by Orbmu2k** [comment]
these are speperate projects

you can find latest inspector beta here
https://www.techpowerup.com/download/nvidia-inspector/
