### ISSUE TITLE
virustotal

### ISSUE THREAD

**Issue by 13menace** [Orbmu2k/nvidiaProfileInspector#125]
MaxSecure security vendor flagged this file as malicious(Trojan.Malware.300983.susgen) on virustotal, can you somehow explain it?
https://github.com/Orbmu2k/nvidiaProfileInspector/releases/download/2.4.0.3/nvidiaProfileInspector.zip

**Comment by Orbmu2k** [comment]
false positive, we are on github, you have the full source!

if you dont trust the CI builds, just build it for yourself :)
