### ISSUE TITLE
Unhandles exception has occured in your application - Cannot open the profile inspector.

### ISSUE THREAD

**Issue by Damthe** [Orbmu2k/nvidiaProfileInspector#128]
I would just kindly like to request for a little help over here.

I am having a bit of trouble while trying to open u p the profile inspector. Only thing i have done on my RTX 3090 is i updated the bios to a Re-Bar version through some sofware available on manufacturer's website(PALIT). I think it has something to do with the NetFramework requirements but i have all of the version installed anyway couldn't really figure out what's wrong here.

Thank you in advance.

![image](https://user-images.githubusercontent.com/21695940/219703042-aea253d7-5b64-4aa4-8bda-bd793ec8b36c.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: BINARY
   at nspector.Common.Meta.CustomSettingMetaService.MapType(String type)
   at nspector.Common.Meta.CustomSettingMetaService.GetSettingValueType(UInt32 settingId)
   at nspector.Common.DrsSettingsMetaService.GetSettingValueType(UInt32 settingId)
   at nspector.Common.DrsSettingsMetaService.CreateSettingMeta(UInt32 settingId)
   at nspector.Common.DrsSettingsMetaService.GetSettingMeta(UInt32 settingId, SettingViewMode viewMode)
   at nspector.Common.DrsSettingsService.CreateSettingItem(NVDRS_SETTING setting, Boolean useDefault)
   at nspector.Common.DrsSettingsService.<>c__DisplayClass18_0.<GetSettingsForProfile>b__0(IntPtr hSession)
   at nspector.Common.DrsSessionScope.DrsSession[T](Func`2 action, Boolean forceNonGlobalSession, Boolean preventLoadSettings)
   at nspector.Common.DrsSettingsServiceBase.DrsSession[T](Func`2 action, Boolean forceDedicatedScope)
   at nspector.Common.DrsSettingsService.GetSettingsForProfile(String profileName, SettingViewMode viewMode, Dictionary`2& applications)
   at nspector.frmDrvSettings.RefreshCurrentProfile()
   at nspector.frmDrvSettings.ChangeCurrentProfile(String profileName)
   at nspector.frmDrvSettings.cbProfiles_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at nspector.frmDrvSettings.frmDrvSettings_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at nspector.frmDrvSettings.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
nvidiaProfileInspector
    Assembly Version: 2.4.0.3
    Win32 Version: 2.4.0.3
    CodeBase: file:///C:/Users/%USERNAME%/Downloads/nvidiaProfileInspector/nvidiaProfileInspector.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by rtzon59** [comment]
same issue here on latest drivers of 1060 6gb and latest win10pro

**Comment by Orbmu2k** [comment]
i really have no idea whats going on there, i can not reproduce it for me and the relevant code part looks just fine 🤔

you can see the mapper there has a valid case for "BINARY"
https://github.com/Orbmu2k/nvidiaProfileInspector/blob/4c28abefa3794784e02ab458bace395382ac721e/nspector/Common/Meta/CustomSettingMetaService.cs#L29

**Comment by Tmp341** [comment]
Same here. It was working before. But i think either after a Windows update or Nvidia update (suspecting Windows update) this issue started. Inspector doesn't even load list. GIF shows error in Turkish, but error still same as i listed below:
![2](https://user-images.githubusercontent.com/1683388/225680011-77f65ba4-f263-4f13-8e92-28dcfe3b2660.gif)

```System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: BINARY
at nspector.Common.Meta.CustomSettingMetaService.MapType(String type)
at nspector.Common.Meta.CustomSettingMetaService.GetSettingValueType(UInt32 settingId)
at nspector.Common.DrsSettingsMetaService.GetSettingValueType(UInt32 settingId)
at nspector.Common.DrsSettingsMetaService.CreateSettingMeta(UInt32 settingId)
at nspector.Common.DrsSettingsMetaService.GetSettingMeta(UInt32 settingId, SettingViewMode viewMode)
at nspector.Common.DrsSettingsService.CreateSettingItem(NVDRS_SETTING setting, Boolean useDefault)
at nspector.Common.DrsSettingsService.<>c__DisplayClass18_0.<GetSettingsForProfile>b__0(IntPtr hSession)
at nspector.Common.DrsSessionScope.DrsSession[T](Func`2 action, Boolean forceNonGlobalSession, Boolean preventLoadSettings)
at nspector.Common.DrsSettingsServiceBase.DrsSession[T](Func`2 action, Boolean forceDedicatedScope)
at nspector.Common.DrsSettingsService.GetSettingsForProfile(String profileName, SettingViewMode viewMode, Dictionary`2& applications)
at nspector.frmDrvSettings.RefreshCurrentProfile()
at nspector.frmDrvSettings.ChangeCurrentProfile(String profileName)
at nspector.frmDrvSettings.cbProfiles_SelectedIndexChanged(Object sender, EventArgs e)
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
at System.Windows.Forms.ComboBox.set_Text(String value)
at nspector.frmDrvSettings.frmDrvSettings_Load(Object sender, EventArgs e)
at System.Windows.Forms.Form.OnLoad(EventArgs e)
at System.Windows.Forms.Form.OnCreateControl()
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl()
at System.Windows.Forms.Control.WmShowWindow(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.Form.WmShowWindow(Message& m)
at nspector.frmDrvSettings.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
nvidiaProfileInspector
    Assembly Version: 2.4.0.3
    Win32 Version: 2.4.0.3
    CodeBase: file:///D:/Program Files/Portable/NVidia/NVIDIA Inspector/nvidiaProfileInspector.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
```

**Comment by Orbmu2k** [comment]
Can you please attach your complete Inspector Folder as ZIP here?

**Comment by Tmp341** [comment]
> Can you please attach your complete Inspector Folder as ZIP here?

[NVIDIA Inspector.zip](https://github.com/Orbmu2k/nvidiaProfileInspector/files/11004000/NVIDIA.Inspector.zip)

> Driver Version?

531.29
> Geforce Experience installed?

No. Only Driver.

**Comment by Orbmu2k** [comment]
> > Can you please attach your complete Inspector Folder as ZIP here?
> 
> [NVIDIA Inspector.zip](https://github.com/Orbmu2k/nvidiaProfileInspector/files/11004000/NVIDIA.Inspector.zip)
> 
> > Driver Version?
> 
> 531.29
> 
> > Geforce Experience installed?
> 
> No. Only Driver.

Still not happen to me with your exact same config. 

Can you pls attach output file of "Export all driver profiles (NVIDIA Text Format)"

**Comment by Tmp341** [comment]
> Can you pls attach output file of "Export all driver profiles (NVIDIA Text Format)" 

[Profiles.txt](https://github.com/Orbmu2k/nvidiaProfileInspector/files/11007702/Profiles.txt)

**Comment by Orbmu2k** [comment]
> > Can you pls attach output file of "Export all driver profiles (NVIDIA Text Format)"
> 
> [Profiles.txt](https://github.com/Orbmu2k/nvidiaProfileInspector/files/11007702/Profiles.txt)

Thanks, but sorry no luck again :( 

This will stay mystery until some other dev having this exact problem on his own machine and is able to debug this by himself.

One thing to try might be to switch your locales to en-US, but no idea.

**Comment by Tmp341** [comment]
> Thanks, but sorry no luck again :(
> 
> This will stay mystery until some other dev having this exact problem on his own machine and is able to debug this by himself.
> 
> One thing to try might be to switch your locales to en-US, but no idea.

It was working normal before. I wasn't using it frequently, so can't pinpoint exact time. But, i suspect some update (My PC got 22H2 around November or December for example) broke it. Especially after formatting my PC, i started getting this. I might try to change language, but it is single language license.

**Comment by Bavarello** [comment]
As far as I'm concerned no problem here with:
Edizione	Windows 10 Pro
Versione	22H2
Data installazione:	‎18/‎06/‎2020
Build sistema operativo	19045.2728
Esperienza	Windows Feature Experience Pack 120.2212.4190.0

![image](https://user-images.githubusercontent.com/22433856/226162865-76032f0b-2164-423c-a5be-dc30d1f1a1fd.png)

**Comment by Tmp341** [comment]
Here are mine:
> Edition : Windows 10 Home Single Language
> Version : 22H2
> Installation Date : 31.‎01.‎2023
> OS Build : 19045.2728
> Windows Feature Experience Pack  : 120.2212.4190.0

**Comment by CanerKaraca23** [comment]
> > Thanks, but sorry no luck again :(
> > This will stay mystery until some other dev having this exact problem on his own machine and is able to debug this by himself.
> > One thing to try might be to switch your locales to en-US, but no idea.
> 
> It was working normal before. I wasn't using it frequently, so can't pinpoint exact time. But, i suspect some update (My PC got 22H2 around November or December for example) broke it. Especially after formatting my PC, i started getting this. I might try to change language, but it is single language license.

I'm also have this issue. Can you try v2.4.0.1? This version works fine for me. Something happened after v2.4.0.3 (v2.4.0.2 not exist).

**Comment by Orbmu2k** [comment]
> I'm also having this issue. Can you try v2.4.0.1? This version works fine for me. Something happened after v2.4.0.3 (v2.4.0.2 not exist).

its known what change in 2.4.0.3 is causing this. 
the problem is related to the BINARY format, what was added to support "Resizeable BAR - Size Limit" setting

the mystery is why does reading the format works on most machines and on some not :)

**Comment by CanerKaraca23** [comment]
> > I'm also having this issue. Can you try v2.4.0.1? This version works fine for me. Something happened after v2.4.0.3 (v2.4.0.2 not exist).
> 
> its known what change in 2.4.0.3 is causing this. the problem is related to the BINARY format, what was added to support "Resizeable BAR - Size Limit" setting
> 
> the mystery is why does reading the format works on most machines and on some not :)

I don't know the mystery but 2.4.0.1 works fine for me. I recommend to use this version until it get fixed. Maybe it's related to Windows version (mine is 11) or .Net Framework (latest 4.8.1 and also enabled 3.5 on Windows Features). I also have the latest version of GeForce Experience, Nvidia Drivers and latest C++ Redistributables.

**Comment by Orbmu2k** [comment]
try newes version pls

**Comment by Tmp341** [comment]
> try newest version please
> 
> https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.4.0.4

This one loaded profiles, without error.

**Comment by Orbmu2k** [comment]
> This one loaded profiles, without error for me.

nice! thanks for the feedback! 

as already guessed, the problem was related to your windows localization settings.

**Comment by Yuuiyfn** [comment]
Hello. I have this issue. Can you help please? 
![Képernyőfelvétel (18)](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/164488924/f929cbb7-a414-48f1-a8a3-e72247325459)

**Comment by HouseQuake** [comment]
> I was getting this error again with latest few versions including pre-release builds. Couldn't update/save profiles with the error either.
> 
> The solution is to delete any files in the C:\ProgramData\NVIDIA Corporation\Drs\ folder. This fixes it, but you will have to remake any custom profiles in NVPI after.

I'd just like to say thank you. This solved it for me.
