### ISSUE TITLE
Possible to remember the window size?

### ISSUE THREAD

**Issue by Blackbird88** [Orbmu2k/nvidiaProfileInspector#13]
Ever since the new update the window is really tiny and its size isn't preserved after exit. Could you please do something about it?

EDIT: In case someone wants the old window size not the tiny window it is now I took 972174a
 and reverted the 58a52d2 commit 
[NVI_big.zip](https://github.com/Orbmu2k/nvidiaProfileInspector/files/1375157/NVI_big.zip)
![image](https://user-images.githubusercontent.com/4414625/43034735-5b677bae-8ce2-11e8-9bc4-1f20e4809ed5.png)

**Comment by DeadManWalkingTO** [comment]
[DeadManWalkingTO/NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)
forked from [Orbmu2k/nvidiaProfileInspector](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)

Release Binaries (New Versions - Updates)

**Comment by Blackbird88** [comment]
Works perfectly! Thank you very much @Orbmu2k ❤
