### ISSUE TITLE
error net framework/ XML

### ISSUE THREAD

**Issue by goap11** [Orbmu2k/nvidiaProfileInspector#131]
![issues](https://user-images.githubusercontent.com/127551673/224424067-525e0e0c-4e3d-40f3-876c-1e605de5cc0c.png)

how i can solve this  issue?

**Comment by Orbmu2k** [comment]
delete c:\Users\<Username>\AppData\Local\NVIDIA Profile Inspector\settings.xml

**Comment by CanerKaraca23** [comment]
> delete c:\Users<Username>\AppData\Local\NVIDIA Profile Inspector\settings.xml

I deleted it but it still gives error. v2.4.0.1 works fine.

**Comment by Orbmu2k** [comment]
should be fixed in https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.4.0.4

**Comment by lauranoe** [comment]
Can you make or be able to make a way to download it on your cell phone? 🙏🙏🙏

**Comment by mathue28** [comment]
![Error 1_15_2024 6_54_19 PM](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/83841156/8b07d30a-b931-485b-8acf-fd05c073fc37)

**Comment by VisualRaks** [comment]
I have that same issue @mathue28

**Comment by Alvin995** [comment]
Me too

**Comment by AbuJassim7** [comment]
![296898678-8b07d30a-b931-485b-8acf-fd05c073fc37](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/171855348/545176a2-0c75-454c-8351-8b86b06b785d)

**Comment by AbuJassim7** [comment]
how i can solve this issue?

**Comment by jabx-777** [comment]
me too pls help 
![Capture d'écran 2024-06-30 175234](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/174269693/eb7f0d13-ac46-4679-bbf9-0faaac00f8c3
![Capture d'écran 2024-06-30 175234](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/174269693/21c22e36-a355-4848-80b2-8505aee1e006)

**Comment by 74diiegx** [comment]
enserio que puedo haver para que no pase eso?

**Comment by KarmaDoesNotMiss** [comment]
im having the same issue , please fix it..

**Comment by Funnyplaz** [comment]
> delete c:\Users<Username>\AppData\Local\NVIDIA Profile Inspector\settings.xml

i tried that and it didnt work

**Comment by kjellurq7** [comment]
![Bild_2024-12-12_155027330](https://github.com/user-attachments/assets/1c7695e0-70c9-4fba-b243-5f3560991b8b)
hello please help me it dosent work
