### ISSUE TITLE
I cannot see this 0x000F00BA 0x000F00BB 0x000F00FF options even though I have resize-bar enable

### ISSUE THREAD

**Issue by NickPolo1** [Orbmu2k/nvidiaProfileInspector#136]
i have a i7-12700k, 32gb ddr4, 3060, win 11. when i try to force enable rezise bar with a specific game i cant find any of the sequences mention in any of the forums or videos on YT. any help would be very appreciated!

**Comment by Orbmu2k** [comment]
![grafik](https://user-images.githubusercontent.com/18091040/229914836-5134ce54-a42b-4ac2-81ff-96bd27765f61.png)
