### ISSUE TITLE
Whenever I try to start the application, this messgage pops up. "The type initializer of 'nspector.Common. Drs ServiceLocator' threw an exception." What do I do. The latest update did nothing. 

### ISSUE THREAD

**Issue by MikeyPlayzonYT** [Orbmu2k/nvidiaProfileInspector#143]
This is the full message. 
The type initializer of 'nspector.Common. Drs ServiceLocator' threw an exception.

em nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan) em nspector.Program.Main(String[] args)

It seems to work for everyone else and I can't find anyone on the web explaining or fixing this is issue. 

Orbmu2k or anyone who knows how to fix this please let me know. 

(Do I need a Nvidia Graphics card perhaps?)

**Comment by Orbmu2k** [comment]
> (Do I need a Nvidia Graphics card perhaps?)

of course you do ^^
