### ISSUE TITLE
Move unknown OpenGL SLI compatibility bits to Compatibility cathegory

### ISSUE THREAD

**Issue by theagentd** [Orbmu2k/nvidiaProfileInspector#15]
Setting 0x209746C1 is the OpenGL SLI compatibility bits. As proof, it's set in the "SLI Test Application" profile, and I need to set that bit to be able to test SLI with the OpenGL game we're developing, and even then it only works in fullscreen. It's currently hidden by default and hard to find as it's classified as unknown, so moving it to the Compatibility tab would be appreciated!

**Comment by Orbmu2k** [comment]
added to v2.30.0
