### ISSUE TITLE
Possible interaction on the AppVeyor binary release from DeadManWalking's fork of this app.

### ISSUE THREAD

**Issue by bjensie** [Orbmu2k/nvidiaProfileInspector#17]
Can you investigate if problem in the title is true? It was bumped in version several times a couple of days ago, probably when DeadManWalking was editing his fork. If true, that would suggest the binary at AppVeyor would be his edit and NOT your original version, which I suppose should stay at 2.1.3.10.

Bengt Jensie

**Comment by Orbmu2k** [comment]
nope its all fine i just played a bit with atomatic release builds from appveyor ;-)

**Comment by bjensie** [comment]
Thanx for your response! Good to hear everything is OK!
