### ISSUE TITLE
This guy is claiming your work as his own

### ISSUE THREAD

**Issue by Freekers** [Orbmu2k/nvidiaProfileInspector#18]
Check out this git repository: https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW
That guy is claiming your work as his own. He didn't change anything beside version numbers and assembly names but did change the copyright to his name. I suggest you contact him to get it sorted.

**Comment by ThetaProtocol** [comment]
DeadManWalkingTO is free to do so. Read the license. Hes done everything required of him by including the license.txt in the repository his changes ot the software if any are allowed and are open source
 

> "Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
> copies of the Software, and to permit persons to whom the Software is
> furnished to do so, subject to the following conditions:
> 
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software."

**Comment by DarkStarSword** [comment]
@ThetaProtocol actually, he was already caught out for violating the license by changing the name in the copyright notices in various files to his own and as a result his repository is only up so long as Orbmu2k doesn't file a DMCA takedown with github:

https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW/issues/1

**Comment by ThetaProtocol** [comment]
Wasn't aware of his previous behaviors, thansk for the info tho. I still like his repos tho now i'm wondering if they exist elsewhere lel

**Comment by Freekers** [comment]
There are still several files where the copyright isn't put in place like it should. But I'll leave it at this.
