### ISSUE TITLE
Weird FPS values?

### ISSUE THREAD

**Issue by Blackbird88** [Orbmu2k/nvidiaProfileInspector#2]
Seriously what is this? :D
The old FPS list was logical.
![image](https://cloud.githubusercontent.com/assets/4414625/14225287/d640b3a6-f8bd-11e5-8891-d61597a3aa69.png)

**Comment by Orbmu2k** [comment]
these are the actual FPS you would see in-game since driver release R341.xx? nvidia changed its implementation of the frame rate limiter, it does not limit to flat FPS anymore.

**Comment by Blackbird88** [comment]
That's weird. Old Inspector always showed the flat values :O
