### ISSUE TITLE
This program does not work for AMD cards?

### ISSUE THREAD

**Issue by Question2** [Orbmu2k/nvidiaProfileInspector#235]
Just wanted to confirm that, its not mentioned on the github page and a quick search just shows tons of people asking the same question but with no direct answers...

Tried launching the program with an AMD card and i got this error instead : 

![image](https://github.com/user-attachments/assets/32bdf5dc-2f90-411a-b947-2e18649d874f)

**Comment by MorbidEden** [comment]
It only works with NVIDIA cards.

**Comment by Question2** [comment]
> It only works with NVIDIA cards.

Is there an up to date utility like this fro AMD cards then?

**Comment by cpbr-dev** [comment]
> Just wanted to confirm that, its not mentioned on the github page and a quick search just shows tons of people asking the same question but with no direct answers...
> 
> Tried launching the program with an AMD card and i got this error instead :
> 
> ![image](https://private-user-images.githubusercontent.com/1191378/386835848-32bdf5dc-2f90-411a-b947-2e18649d874f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzgwNDIsIm5iZiI6MTczMTc3Nzc0MiwicGF0aCI6Ii8xMTkxMzc4LzM4NjgzNTg0OC0zMmJkZjVkYy0yZjkwLTQxMWEtYjk0Ny0yZTE4NjQ5ZDg3NGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMTcyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzIyODVlYTI4YzljYjczNWIwYTQxMDMxNDFlOTZjOTUzZTI5OTAzMGM1YWJkZjAzNTcxZTlhNzQxNGJkMTVkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gzUiaEX9DjdNJkpx8wgODABwUkmIXX1V7E6c6AbEGMY)

From the Readme file
> This tool is used for modifying game profiles inside the internal driver database of the **nvidia** driver. 
I would assume the name of the program being **Nvidia** Profile Inspector is a good enough hint.

**Comment by MorbidEden** [comment]
> > It only works with NVIDIA cards.
> 
> Is there an up to date utility like this for AMD cards then?

None that I am aware of. Sorry.
