### ISSUE TITLE
Add application to custom profile (not working)

### ISSUE THREAD

**Issue by false-9** [Orbmu2k/nvidiaProfileInspector#25]
GTX 670, Windows 10

Have not had any success creating a custom profile and then adding an application to it for frame limiter usage. Inspector says the application is added, but settings changes don't take effect, and settings changed from nvidia control panel don't appear in inspector for the game in question either as they usually would. Settings work for the games that already have predefined profiles but when Custom Profile > Add application they do not.

Have tried as early as v1.9.9.5 and no luck either, this is something that has been bothering me for a while, I just want to play Ori and the Blind Forest with a frame limiter, preferably using nVidia inspector.

**Comment by Orbmu2k** [comment]
you probably choose the wrong exe, take a look in taskmanager while game is running what the exact exe name is.
