### ISSUE TITLE
Inspector is unable to import nvidia format because of the use of wild card sign * in Siemens Teamcenter gdr*.exe

### ISSUE THREAD

**Issue by Squall-Leonhart** [Orbmu2k/nvidiaProfileInspector#27]
Assumedly because inspector uses an older version of the api, which has since been fixed

ie: Geforce 3D Profile Manager used to fail on this same profile, but it now works without change since the driver updated to 397.

**Comment by Orbmu2k** [comment]
if its fixed by driver for Geforce 3D Profile Manager then its fixed for inspector to, bot using the same API.

**Comment by Squall-Leonhart** [comment]
Negative, Profile inspector cannot import the profile, the nvidia utility can.

**Comment by Orbmu2k** [comment]
sry i can not reproduce that here :( [R418.81 WIN10]

1. exported all profiles in nvidia format
2. imported all profiles in nvidia format => success!
3. changed some settings in siemens teamcenter profile
4. imported all profiles in nvidia format => success!
5. exported siemens teamcenter profile in NIP format
6. imported siemens teamcenter in NIP fromat => success!
7. exported all profiles in nvidia format
8. imported all profiles in nvidia format => success!

no idea!

**Comment by Squall-Leonhart** [comment]
Found it i think

Profile Inspector fails the import because i have a custom profile that includes Dolphin.exe.

Profile "Emulators Nintendo GameCube/Wii" UserSpecified=true
    ShowOn All
    ProfileType Application
    Executable "dolphin.exe" FindFile="sys/wii/shared2/wc24/nwc24dl.bin"
    Setting ID_0x00d55f7d = 0x00008000 UserSpecified=true
    Setting ID_0x101e61a9 = 0x00000010 UserSpecified=true
    Setting ID_0x107efc5b = 0x00000000 UserSpecified=true
    Setting ID_0x10d2bb16 = 0x00000001 UserSpecified=true
    Setting ID_0x701eb457 = 0x2241ab21 InternalSettingFlag=V0
    Setting ID_0x7050e011 = 0x7498ee8d InternalSettingFlag=V0
    Setting ID_0x709a1ddf = 0x4b1cd96b InternalSettingFlag=V0
    SettingString ID_0x70b5603f = "D3D"
    Setting ID_0x70edb381 = 0x24208b6c InternalSettingFlag=V0
    Setting ID_0x80857a28 = 0x00000000
EndProfile

The default profile set includes Dolphin.exe under

Profile "Dolphin Emulator"
    ShowOn GeForce
    ProfileType Application
    Executable "dolphin.exe" FindFile="sys/wii/shared2/wc24/nwc24dl.bin"
    Setting ID_0x701eb457 = 0x2241ab21 InternalSettingFlag=V0
    Setting ID_0x7050e011 = 0x7498ee8d InternalSettingFlag=V0
    Setting ID_0x709a1ddf = 0x4b1cd96b InternalSettingFlag=V0
    SettingString ID_0x70b5603f = "D3D"
    Setting ID_0x70edb381 = 0x24208b6c InternalSettingFlag=V0
    Setting ID_0x80857a28 = 0x00000000
EndProfile

My custom set removes the Dolphin Emulator profile, and adds Emulators Nintendo GameCube/Wii

There is a difference in  behavior between the inspector tool and 3D Profile manager here, the profile tool is overwriting all profiles without any consideration for existing profiles, where Profile Inspector is somehow seeing a clash between the profiles.

**Comment by Squall-Leonhart** [comment]
minimised reproduction
[Profiles.zip](https://github.com/Orbmu2k/nvidiaProfileInspector/files/2898247/Profiles.zip)
