### ISSUE TITLE
It is trojan here in that project

### ISSUE THREAD

**Issue by believer-ufa** [Orbmu2k/nvidiaProfileInspector#28]
I think people need use original project that that.

![image](https://user-images.githubusercontent.com/801727/50575918-d403a480-0e28-11e9-98c1-d5f67ae788cf.png)

**Comment by DarkStarSword** [comment]
As suspicious as I am of his fork, virustotal gives that release a clean rating:
https://www.virustotal.com/#/url/9b88a17bbbd5d5820abe1110b59997a525394996e2874b66b1d1f1adc80a6d31/detection

**Comment by believer-ufa** [comment]
Sorryy!! Im about that fork: https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW/issues/14.
