### ISSUE TITLE
Is The Project Still Alive?

### ISSUE THREAD

**Issue by 0pLuS0** [Orbmu2k/nvidiaProfileInspector#29]
Hello,

Been reading online, trying to find a decent Gaming Profile app, in the past when it was alive I used nHancer.

Not sure if I know this app, Nvidia Inspector.

Everywhere I read, this gets good praise, but I don't see any commits or work going on, so wondering is this project dead?

The way Nvidia puts out drivers all the time, I assumed for something like this, it would need constant current development.

So I'm not sure if this latest version is still good on the latest hardware and drivers out there? It was relased a year ago... 

Hmm

**Comment by DarkStarSword** [comment]
I can't speak for the dev or his plans, but the driver profile management hasn't really changed that much in forever (biggest upset I can think of was the 3D Vision encrypted settings) and this still works fine and is actively used by everyone in the 3D Vision and SLI modding communities today.

**Comment by 0pLuS0** [comment]
Ok...

One question, without opening an "Issue" on it, I saw online, to use this, all I have to do is go to the drop down, pick a game and then apply, is that all there is to it?

I looked for Ring of Elysium, then clicked apply...

From what I understand, everything in "Green" are the new changes, but Ring of Elysium only had like 2 sections in green, and I was like great, there isn't much tweaking for this game... sad... :(

**Comment by Orbmu2k** [comment]
Light Gray - setting is no set (default)
Dark Gray - shadow user setting inherited from global profile
Green - setting predefined by NVIDIA
Blue - setting changed (and applied) by user

what did you expect that tool to do for you? 
this tool doesnt magicly/automatic tweaks anything ;-) 

you can tweak everything, if you need to and know what you do.

if you want somewhat automatic optimzation -> "Geforce Experience" ist the right tool four you ;-)

**Comment by Orbmu2k** [comment]
you might want to take a look at this tutorial
https://wiki.step-project.com/Guide:NVIDIA_Inspector

**Comment by 0pLuS0** [comment]
@Orbmu2k

Sorry for my last reply, I didn't explain myself very well, I'm a Geek I like to tweak, I guess some information I saw online wasn't correct, I only read a little about nvidiaProfileInspector.

I know it's for customizing settings, I was under the impression that the Green settings were changes added to the games, what I mean by this is, hidden features in Nvidia, that unless you access them, then they are not activated, and nvidiaProfileInspector does this.

Then, beyond accessing these hidden settings now added, the end-user can further tweak any other settings they way...

You should put some links in the Readme.md on Github to point people to documentation...

Thanks

**Comment by 0pLuS0** [comment]
@Orbmu2k

Sorry for my last reply, I didn't explain myself very well, I understand the customization of Inspector. I just thought from what I was reading online that the Green sections were hidden settings accessed with the Inspector...

I have a bookmark already for that Wiki, I've only browsed through it. By the way the ```Nvidia Inspector``` is it still getting development? I have a GTX 1060 6GB, wondering how the support is on it?

The AA settings I am using don't fully remove jagged edges, and I read with these settings it won't 100%, and DSR is suppose to be the only way for the best performance, with less of a hit on the GPU.

I've always thought the AA settings in the driver will fully remove jagged edges, I know in the past some games this did work.

In the game settings of ROE if AA is placed on high all the jagged edges are gone, but going this way is a performance hit, so I'm trying to figure out how to fully get rid of the jagged edges without a performance loss in ROE using Inspector.

If someone can please look at my ROE profile from Inspector and tell me what you think, I would really appreciate it.

Thanks

[Ring of Elysium.nip.zip](https://github.com/Orbmu2k/nvidiaProfileInspector/files/2883191/Ring.of.Elysium.nip.zip)

**Comment by Orbmu2k** [comment]
if nothing helps try FXAA ;-)

**Comment by 0pLuS0** [comment]
FXAA makes it a little blurry...

No worries I'm working it out, but with a Game like ROE, not sure nvidiaProfileInspector can help much, it doesn't seem to allow much outside tweaking and there's not much room for it either, at least it appears that way...
