### ISSUE TITLE
Hi could you add variable fan control ... when temperatures go up the fan increases speed rather then a fixed speed or auto. thx

### ISSUE THREAD

**Issue by auroracoin** [Orbmu2k/nvidiaProfileInspector#3]
Hi could you add variable fan control ... when temperatures go up the fan increases speed rather then a fixed speed or auto. thx

**Comment by Orbmu2k** [comment]
this project is nvidia PROFILE inspector, your request is targeted to the legacy inspector tool

**Comment by auroracoin** [comment]
Sorry I don't know the difference between the two they seen the same
