### ISSUE TITLE
Minimize to tray || Close to tray?

### ISSUE THREAD

**Issue by DeadSeriousBros** [Orbmu2k/nvidiaProfileInspector#30]
Would like to see "**Minimize to tray**", and maybe even an option for "**Close to tray**" as well. **Thanks!** PS: I have tried a few programs such as "**RBTray**", "**Trayconizer**", and "**Actual Window Minimizer**" and _**none of them seem to work**_ for this program specifically...

**Comment by Orbmu2k** [comment]
why would you? there is no need to let this tool running in background!

**Comment by DeadSeriousBros** [comment]
Would be easier to access when needing to change settings for a newly added game. Instead of opening again/searching for it, and auto updates/update checking could be added later so leaving it up would keep it up-to-date as well, Also would not be asking if it would work in any other "Program to tray" application, although with that said, it is completely up to you whether or not you add it in. Either way thank you for answering me and acknowledging my suggestion. ✋😄

**Comment by Orbmu2k** [comment]
i dont get the point, for ongoing tweaking on a single profile u can just minimize it.

if you want to find your profile fast after starting the tool, there are two ways:

1.) the dropdown right to the home button only conatains your "modified profiles"
2.) just drag n drop the shortcut to your game onto profile inspector tool, it will open the profile for it, or ask to create a new one if none found
