### ISSUE TITLE
Make NvidiaProfileInspector Portable

### ISSUE THREAD

**Issue by ImSpecial** [Orbmu2k/nvidiaProfileInspector#33]
Hi, lovely tool! I notice now with v2.3.0.2 a settings.xml file is created in AppData\Local\ which saves windows positions, etc. can this file be moved to the "nvidiaProfileInspector" folder or if a settings.xml is already detected inside use that one instead? This would make nvidiaProfileInspector portable and much better in my opinion, having settings for many in different locations with no user knowledge is such a plague nowadays.

**Comment by yoelXXX** [comment]
Ok

**Comment by softlines** [comment]
This wouldn't make it portable necessarily if it still edits the registry.
