### ISSUE TITLE
First time using this 

### ISSUE THREAD

**Issue by Cupcakes123** [Orbmu2k/nvidiaProfileInspector#35]
Hello,

A friend recommended me this program and I noticed everytime I change my "profiles" > hit apply changes > close out and reopen the Nvidia inspector again.. the profile goes back to "_GLOBA_DRIVER_PROFILE (Base Profile)" 

I was wondering if this is normal? I wasn't sure if the profile had to be set to a specific game for it to work.

Thank you for your time.

**Comment by Hexaae** [comment]
When you (re)start NPI yes, it's normal it opens on global profile.
You have one only global cfg (just like in NVidia driver control panel) + single configurations for every game. You can even add your own cfgs clicking on the small 'new' sun icon ☀, just remember to add ➕ also the targeted exe(s).
Of course single configs will overwrite in priority global config.
