### ISSUE TITLE
Disable DXR possible?

### ISSUE THREAD

**Issue by Cris--** [Orbmu2k/nvidiaProfileInspector#36]
Hi,

it's not really an issue, more a feature request.
I have a 1070Ti and if there are techdemos like [Attack from Outer Space](https://youtu.be/tf95_ukvZ-o) with raytracing and DXR i get 8 FPS. But i can't disable DXR (nor ingame option or config i think) to get more FPS to enjoy this techdemo!

**Comment by ValZapod** [comment]
@Orbmu2k Yeah, good question. BTW, are you maintaining this repo?

**Comment by Orbmu2k** [comment]
if someone find such setting i will add it, but i dont think its somthing like that will exist

**Comment by mirh** [comment]
Aaand it's done https://github.com/Orbmu2k/nvidiaProfileInspector/commit/75c99ea6c71a522835aac785fcb1af7480c2664b
