### ISSUE TITLE
Two requests: save profile as text, and add mouse-wheel support to pop-up user profiles menu

### ISSUE THREAD

**Issue by Hexaae** [Orbmu2k/nvidiaProfileInspector#38]
1. save a profile as html text (with colors for changed settings...) to be shared on Steam threads etc. and help people copy-pasting suggested custom settings
2. use mouse-wheel to scroll up/down in the pop-up menu if you have a very long list of customized profiles

**Comment by Orbmu2k** [comment]
added a CTRL+C feature for copy modified settings as plain text to clipboard
