### ISSUE TITLE
Whats are the parameters?

### ISSUE THREAD

**Issue by andreluizbarbieri** [Orbmu2k/nvidiaProfileInspector#4]
Congratulations for your app. I need a parameter for "nvidiaprofileinspector.exe nameprofile.nip **here**", where I wouldn't need to click on OK button. I want change profile via prompt without dialog box.

**Comment by Orbmu2k** [comment]
some people might say "use the force, read the source" :)

the param you look for is: "-silent" or "-silentImport"

**Comment by andreluizbarbieri** [comment]
But this parameters open the nvidiaProfileinspector window. I want a real silente that I can run via prompt without generate window(with -silent)/dialog box(whitout).

**Comment by Orbmu2k** [comment]
did you even use the latest build? 

https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts

"-silentInport" needs at least v2.1.2.1
"-silent" needs at least v2.1.2.4

**Comment by andreluizbarbieri** [comment]
Thanks Man!

**Comment by auroracoin** [comment]
Hi I can't find nvidiaProfileInspector thread... what is it plz  thx

**Comment by andreluizbarbieri** [comment]
@auroracoin This thread is closed. Because it was resolved. I did want run in cmd.exe this: "nvidiaprofileinspector.exe nameprofile.nip -silent" and now it Works!
