### ISSUE TITLE
Slow startup after installing Nvidia driver 436.02

### ISSUE THREAD

**Issue by tesla2105** [Orbmu2k/nvidiaProfileInspector#41]
After installing driver version 436.02, profile inspector startup is really slow. This is probably because of the new settings introduced in this new driver (Ultra-Low Latency and Integer Scaling).

**Comment by Gordon-Dry** [comment]
That driver is creating stutter issues for many people, also for me.
I already reverted it to the prior version.

This could lead into a fixed version next week.

**Comment by Orbmu2k** [comment]
this is totally driver related, no headroom for optimization left :(

you may try the "-disableScan" parameter, but then you dont have the modified profile list and other scan realted features
