### ISSUE TITLE
Start in Tray mode

### ISSUE THREAD

**Issue by SaulGoodman1337** [Orbmu2k/nvidiaProfileInspector#42]
Hi,
Is it possible to Start in minimized or better in Tray mode ?
Greetings Saul

**Comment by bjensie** [comment]
Why would you like to do that? You only use this tool to configure the driver, then you close it!

**Comment by SaulGoodman1337** [comment]
For automation.
I call the tool via different Powerscripts which are called at different conditions. 
If there is no possibility to start the program in the tray, I have to look somewhere else.

**Comment by bjensie** [comment]
Okay, I was just curious. Let's see if you can get an answer from Orbmu2k about it!

**Comment by Orbmu2k** [comment]
if you configure driver via import nip files use the "-silent" parameter.

there is no need for this tool to run in background, so no need for tray either
