### ISSUE TITLE
Some Features Don't Work

### ISSUE THREAD

**Issue by mstfbsrn980** [Orbmu2k/nvidiaProfileInspector#49]
Ultra Low Latency and Sharpenning features do not work with the new nVidia display driver (445.87). I also contacted nVidia. And nVidia technical support staff stated that this is not driver-related. She stated that there is no change preventing third party software from working.

**Comment by Orbmu2k** [comment]
tech support might not be fully aware of this problem, but its totally driver related, as you can just downgrade the driver to get it work again ;-)

also the fact, that just a very limited amount of settings are affected, leads to this conclusion, as every single setting is handled the same way form this tool.

**Comment by mstfbsrn980** [comment]
I requested that the issue be forwarded to the developer engineer of nVidia display driver. I hope they will solve the problem... Thanks for your reply...

**Comment by Q3BFG10K** [comment]
FYI - I tested 446.14 and can confirm using nVidia's very old profile tool, Ultra Low Latency is correctly saved and restored using the exported text file.

It might be worth re-testing Inspector as it'd be really nice if the .nip files could also have this functionality.
