### ISSUE TITLE
Error when importing profiles

### ISSUE THREAD

**Issue by Blackbird88** [Orbmu2k/nvidiaProfileInspector#5]
Happens when I try to import profiles I exported as **backup.nip** (1.9.7.6)

https://gist.github.com/Blackbird88/a4676a055cafa64a12a4a0b2be4c12ae

It works perfectly fine in 1.9.7.3

**Comment by Orbmu2k** [comment]
this schould be fixed since build 2.1.2.4, please try the latest build:
https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts

**Comment by Blackbird88** [comment]
Yup, it's fixed now.
gj
