### ISSUE TITLE
Silk Smoothness Option Missing

### ISSUE THREAD

**Issue by Aethelric** [Orbmu2k/nvidiaProfileInspector#50]
There used to a option called 'Silk Smoothness' in Nvidia Profile Inspector. Its missing in latest driver 445.87. Does the driver not contain the option or Nvidia Profile Inspector not picking it up?

**Comment by ArtanisInc** [comment]
U can make it visible on NVIDIA Control panel, add this reg key

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\nvlddmkm\FTS]
"EnableRID61684"=dword:00000001`

BTW Some settings can no longer be called with NVIDIA API, that is why silk smoothness is missing on NVIDIA profile inspector

**Comment by Aethelric** [comment]
> U can make it visible on NVIDIA Control panel, add this reg key
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\nvlddmkm\FTS]
> "EnableRID61684"=dword:00000001
> ```
> 
> BTW Some settings can no longer be called with NVIDIA API, that is why silk smoothness is missing on NVIDIA profile inspector

Thank you, this worked but will the option return in NPI? Also can we also add other options not natively supported in NVIDIA Control Panel? If so how do I go about doing that?

**Comment by Aethelric** [comment]
I encountered a problem. In NVIDIA Control Panel I can select the 'Silk Smoothness' option in Global settings but not per application. 

![silkncp2](https://user-images.githubusercontent.com/65872787/82922709-93fe0e00-9f97-11ea-825d-d74e1e785e7c.png)

![silkncp](https://user-images.githubusercontent.com/65872787/82922810-b7c15400-9f97-11ea-8e14-28d9767369ed.png)

Also even though it says ultra in Global setting I dont think it works in game. Witcher 3 stutters semi frequently. With this setting ON it should reduce them significantly but it does not. Any suggestions?

**Comment by Orbmu2k** [comment]
first of all, i guess this feature has been removed completly from the driver

i also tried to manually write the per game "allow silk smoothness" setting 0x00666634 but this settingid is also affected by this driver restriction #46 #49 

so the only option is a driver downgrade, sry :(
