### ISSUE TITLE
how is this different from the version in NVIDIA Inspector?

### ISSUE THREAD

**Issue by softlines** [Orbmu2k/nvidiaProfileInspector#52]
The one from NVIDIA Inspector is version 2.13. This one is 2.3.0.12. Which one is current?

**Comment by ValZapod** [comment]
It does not update the virsion unless the "stable" released? Dunno.

**Comment by Orbmu2k** [comment]
github has always the latest version of course

nvidia inspector just ships the version which was stable on the release of nvidia inspector itself long long time ago. 😉
