### ISSUE TITLE
Frame Rate Limiter parameter defaults to "0xB0C02000"

### ISSUE THREAD

**Issue by RodroG-85** [Orbmu2k/nvidiaProfileInspector#53]
Hi @Orbmu2k, is "0xB0C02000" the intended default value for the `Frame Rate Limiter` parameter? Shouldn't be "Off" its default value instead?

On my end, with NVIDIA defaults the `Frame Rate Limiter Mode` shows "Default" value and `Frame Rate Limiter V3` to "Off" but `Frame Rate Limiter` defaults to "0xB0C02000". Is this intended? Please, some clarification will be very appreciated.

![frame_rate_limiter_default_0xB0C02000](https://user-images.githubusercontent.com/56508839/87193441-fff2c680-c2f8-11ea-910c-796eaac1f57b.png)

Thanks in advance and kind regards.

**UPDATE:** After some testing, it seems that currently the value "0xB0C02000" is necessary for the new NV CP limiter (V3) to work properly and its corresponding selected FPS to apply. This doesn't occur when the value "Off" is set for `Frame Rate Limiter`. For example, in this case and if 158 FPS is set for the V3 limit, the limiter applies 160 FPS in-game as limit and not 158 fps.

**Comment by ValZapod** [comment]
Is default done in the app? I think the defaut is defined n the driver.

**Comment by RodroG-85** [comment]
As far I know, yes, it's default in the driver and reflected and shiwed by
the app. However, the default value changed recently on my end (previously
the default was "Off"). Then my question, I'd highly appreciate if @Orbmu2k
could clarify and confirm the situation here.
