### ISSUE TITLE
nvidiaInspector

### ISSUE THREAD

**Issue by Hunter23071985** [Orbmu2k/nvidiaProfileInspector#60]
Hello!
Please combine the [nvidiaInspector](https://orbmu2k.de/tools/nvidia-inspector-tool) and [nvidiaProfileInspector](https://github.com/Orbmu2k/nvidiaProfileInspector/releases) utilities into one program.
Sincerely.

**Comment by Orbmu2k** [comment]
you came just 10 years too late! :-D

sry will not happen!

**Comment by Hunter23071985** [comment]
Will nvidiaInspector be further developed? If not - why?
