### ISSUE TITLE
NVAPI_NOT_SUPPORTED attempting to set "Enable Ansel" to off within the _GLOBAL_DRIVER_PROFILE

### ISSUE THREAD

**Issue by xeropresence** [Orbmu2k/nvidiaProfileInspector#62]
This was working for me up until around driver 457.09 I think, since past that it now throws NVAPI_NOT_SUPPORTED

**Comment by Orbmu2k** [comment]
the driver comes with more an more restrictions

but you can globally disable ansel with this tool
c:\Program Files\NVIDIA Corporation\Ansel\NvCameraConfiguration.exe

**Comment by shimaowo** [comment]
That Ansel folder hasn't existed for a while now, not sure where things have moved.  Kind of annoying since now there is seemingly no way to disable ansel at all on current drivers.

**Comment by shimaowo** [comment]
For anyone else looking, this might work for disabling ansel - it seems to with one game, but I haven't tested much yet.

* Open an admin cmd prompt, navigate to `C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_<your driver version>\NvCamera`
  * (for me, the current driver folder is `nv_dispi.inf_amd64_a51067c0ac557884` )
* Run `NvCameraEnable.exe off`

Assuming this does actually work consistently, it probably has to be done every time you download a new driver.

**Comment by Hrxn** [comment]
What if there are two directories with `nv_dispi.inf_amd64_<someID>`?

**Comment by Orbmu2k** [comment]
@shimaowo 
for me this folder is still present. do you have DCH version of the driver installed?

**Comment by shimaowo** [comment]
@Orbmu2k This is a relatively new windows install, with the nvidia driver through geforce experience.  From scanning some of the configuration files, I think Ansel was rolled into some of the other components recently.  My guess is that maybe any "old" Ansel folder isn't removed with new driver installations, and perhaps the config tool still works, but it is no longer installed into Program Files with the new drivers.  I definitely used to have the folder on my older windows install at some point, but I don't have that around anymore to see if the folder would have been removed.

@Hrxn You can probably just pick the folder with the newer date (I also had 2).  There's probably a more deterministic way to figure it out by looking into the files or the registry, but this was just a quick hack (and I'm lazy)
