### ISSUE TITLE
Frame Limiter Mode error (2021)

### ISSUE THREAD

**Issue by EdmondScorp** [Orbmu2k/nvidiaProfileInspector#63]
After the latest Nvidia Driver update (461.09) I cannot change the Frame Limiter Mode, its set to **0x00000088** by default and does not allow me to change to any value. What's the issue?

**Comment by shadowspike74** [comment]
me aswell

**Comment by Orbmu2k** [comment]
![grafik](https://user-images.githubusercontent.com/18091040/104820846-05951000-5838-11eb-8afd-1da2beaac0de.png)

**Comment by EdmondScorp** [comment]
So any further updates to Nvidia drivers will have this removed? I guess
I'ma stay on mine forever then :P Because when I am playing csgo I can
greatly feel the input lag difference.

**Comment by Orbmu2k** [comment]
Yes but Framelimiter v3 schould be as good as the fastest v1 mode. At least combined with Ultra Low Latency Mode.
