### ISSUE TITLE
DRS_SetSetting failed: NVAPI_SETTING_NOT_FOUND

### ISSUE THREAD

**Issue by Rokeugon** [Orbmu2k/nvidiaProfileInspector#65]
Recently just migrated over to a larger boot SSD. and was going through trying to sort out everything again but ive gotten a error which i have no clue in how to fix as there is no info available to me. so far ive tried deleteing the Drs folder and then recreating it aswell as uninstalling nvidia drivers completely and doing a clean install. but so far that doesnt seem to have fixed the issue 

![setting no found](https://user-images.githubusercontent.com/5246538/104892996-c87d6a80-596a-11eb-81c5-98f0bac3ab86.png)

> here is the exception text:
> ************** Exception Text **************
> nspector.Common.NvapiException: DRS_SetSetting failed: NVAPI_SETTING_NOT_FOUND
>    at nspector.Common.DrsSettingsServiceBase.StoreDwordValue(IntPtr hSession, IntPtr hProfile, UInt32 settingId, UInt32 dwordValue)
>    at nspector.Common.DrsSettingsService.<>c__DisplayClass15_0.<StoreSettingsToProfile>b__0(IntPtr hSession)
>    at nspector.Common.DrsSettingsServiceBase.<>c__DisplayClass5_0.<DrsSession>b__0(IntPtr hSession)
>    at nspector.Common.DrsSessionScope.DrsSession[T](Func`2 action, Boolean forceNonGlobalSession, Boolean preventLoadSettings)
>    at nspector.Common.DrsSettingsServiceBase.DrsSession(Action`1 action, Boolean forceNonGlobalSession, Boolean preventLoadSettings)
>    at nspector.Common.DrsSettingsService.StoreSettingsToProfile(String profileName, List`1 settings)
>    at nspector.frmDrvSettings.StoreChangesOfProfileToDriver()
>    at nspector.frmDrvSettings.tsbApplyProfile_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ArtanisInc** [comment]
some settings about frame rate limiter got removed
![image](https://user-images.githubusercontent.com/20884381/104973876-75e99000-59f6-11eb-81f9-9a3eb072b848.png)

**Comment by EtRnitY** [comment]
Hi.
I have the same issue and I think this problem appeared with the latest Nvidia driver 461.09
I started to have the issue after updating to 461.09
 
I think the only fix is to uninstall the latest Nvidia driver and install the previous one (460.89) from Nvidia website : https://www.nvidia.com/Download/index.aspx?

**Comment by Orbmu2k** [comment]
try this version https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.3.0.13
i removed deprecated settings
