### ISSUE TITLE
will the old framelimter be added back if can be fixed

### ISSUE THREAD

**Issue by shadowspike74** [Orbmu2k/nvidiaProfileInspector#66]
version 3 dose not work for my pc and the last version had an error after updating my drivers I do hope to see it return in the meantime I'm gonna have to stick with the v-scan settings for some of my games for now please let me know what's happening with it

**Comment by Orbmu2k** [comment]
nope it will not come back it has been removed from the nvidia driver.

if version 3 does not work for you, fell free to report a bug to nvidia

**Comment by shadowspike74** [comment]
well when I set the framerate on framerate limter V.3 it dose nothing I wish I can set my fps to something like 25 or 50fps for colin mcrae rally 3 which has fps problems

**Comment by Orbmu2k** [comment]
if the DirectX version is below "9ex" its not supported, i guess ist just version 9 without "ex". consider to use rivatuner statistics server in this case

**Comment by shadowspike74** [comment]
I have a Nvidia GTX GeForce 1660 super graphics card which has DirectX 12 and OpenGL as well as vulken. I have only had the graphics card for a year and it still works fine my pc is not a very high end one. I still need to update my 4 year old cpu thats not a very high end one. it can play games like half life 2 at 60fps just fine team fortress 2 on the other hand runs like trash on my pc i'm just asking is there anyway to fix this if not then that's ok i'll just have to use the control panel

**Comment by Orbmu2k** [comment]
I was talking about that game, its a very old game which targets to an old DirectX API.

You have two options. 

1. Rollback nvidia driver down to a version where old fps limiter still works and use an old version of profile inspector with this setting still included.

2. use riva tuner statistics server for fps limiting instead

**Comment by spike74** [comment]
OK just had to restart my pc I realised I installed an expered version of Macfee
