### ISSUE TITLE
app.config is empty

### ISSUE THREAD

**Issue by LethalManBoob** [Orbmu2k/nvidiaProfileInspector#68]
Cannot be built 
![image](https://user-images.githubusercontent.com/30273211/106918002-bb010800-6700-11eb-9917-44238db46a49.png)

**Comment by Orbmu2k** [comment]
there is no "app.config" in this project

the build works just fine, see here
https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/builds/37328259

may be related to your build system
