### ISSUE TITLE
Internal settings are not correctly decoded, and are corrupted if they are written back

### ISSUE THREAD

**Issue by DarkStarSword** [Orbmu2k/nvidiaProfileInspector#7]
The internal settings are encrypted, so the values shown in the tool for these are garbage and inconsistent with the equivalent settings on a user profile. Further, if these are written back they will lose the internal setting flag, causing them to be treated as though they were not encrypted, effectively corrupting them.

A 2048 bit key is used, and the Setting ID is used to derive an offset into that key ((ID * 2) % 256) that is then XORed against the value. In the case of strings this is a byte by byte XOR, and in the case of DWORDs the key is read as a 32bit little-endian value from the correct offset and XORed against the value. If the end of the key is reached it wraps back to the start.

This script may be of interest to show how to decrypt these values:
https://raw.githubusercontent.com/DarkStarSword/3d-fixes/master/__profiles__/sanitise_nv_profiles.py

**Comment by Orbmu2k** [comment]
Thanks for this! I made a first test build you can check out:
https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts

**Comment by DarkStarSword** [comment]
Excellent - just gave it a try and it looks perfect :)
