### ISSUE TITLE
No Main Window? Only Driver Profile Settings?

### ISSUE THREAD

**Issue by DraziaXardei** [Orbmu2k/nvidiaProfileInspector#70]
Like stated above, I can't get the main info window to pop up. I'm mainly looking for your programs info on my card but it's all good. Don't really need to change settings so this is kinda obsolete for me.

**Comment by Yuvix25** [comment]
Happened to me as well.

**Comment by Orbmu2k** [comment]
This project is the Profile Editor only! Its called "nvidia**Profile**Inspector" 😉
