### ISSUE TITLE
Request: resizable bar manipulation 

### ISSUE THREAD

**Issue by yamaci17** [Orbmu2k/nvidiaProfileInspector#75]
is it possible to manipulate resizable bar and force-enable it in games through nvidia profile inspector?

**Comment by PhantomGamers** [comment]
Yes, it's these three settings

![image](https://user-images.githubusercontent.com/844685/113369097-7378b000-932e-11eb-9930-f2152b052c08.png)

0x000F00BA, 0x000F00BB, 0x000F00FF

**Comment by yamaci17** [comment]
thank you a lot
