### ISSUE TITLE
NVIDIA Inspector - Official place to report issues?

### ISSUE THREAD

**Issue by TIGwelder-42** [Orbmu2k/nvidiaProfileInspector#76]
Noticing an issue with NVIDIA Inspector 1.9.8.1, but having a hard time finding a place to report it.

If you use command line to set -setBaseClockOffset with NVIDIA Inspector closed, it will set the Base Clock Offset properly, but when you open the app the Base Clock Offset slider will be at 0 Mhz even though the setting is currently applied

If you run the command line option with Inspector open, it will move the slider to the correct place and set the Base Clock Offset properly.

Very confusing when trying to test whether batch files are working properly.

**Comment by ivnish** [comment]
I confirm this bug

**Comment by autolycosII** [comment]
Can confirm as well.
