### ISSUE TITLE
Since nvidia released the nvapi sdk, is it not possible to design this for linux?

### ISSUE THREAD

**Issue by LethalManBoob** [Orbmu2k/nvidiaProfileInspector#83]
Since nvidia released the nvapi sdk, is it not possible to design this for linux?

**Comment by Orbmu2k** [comment]
as far as i understand this "release", nvidia just opened the interface internals to 3rd parties for mocking nvapi in wine/dxvk environments

there is no real NVAPI module or DRS options in the linux driver for my knowledge

**Comment by LethalManBoob** [comment]
Alright, my mistake. Thanks for the info.

**Comment by dougg0k** [comment]
Hey @Orbmu2k would it be possible now with the open modules?

https://developer.nvidia.com/blog/nvidia-transitions-fully-towards-open-source-gpu-kernel-modules/

**Comment by ThomasEricB** [comment]
I would also like to know
