### ISSUE TITLE
Nvedia Frame Rate Limiter mode option not available

### ISSUE THREAD

**Issue by hiofficial4477** [Orbmu2k/nvidiaProfileInspector#84]
Hi , I like your NVIDIA inspector so much but in the (version 2.3.0.10)  Frame rate limiter mode does not work it always says DRS_Set Setting failed : NVAPI_SETTING_NOT_FOUND .
and the real problem is i can't downgrade my NVIDIA drivers cause I have 3060 ti ( NVIDIA drivers Ge force 466.47) and it is the lowest i can downgrade my drivers to.
Please I beg you can you update the app and make Frame rate limiter mode run on (NVIDIA drivers Ge force 466.47) please.
If not can you suggest how can  I manually change this settings and from which file. 
Thank you.

**Comment by Orbmu2k** [comment]
sorry, but this switch just doesn't exists anymore in newer drivers. so there is nothing to toggle here.
