### ISSUE TITLE
Error: Exception NVIDIA API not supported

### ISSUE THREAD

**Issue by HorselessName** [Orbmu2k/nvidiaProfileInspector#87]
************** Exception Text **************
nspector.Common.NvapiException: DRS_SetSetting failed: NVAPI_NOT_SUPPORTED

I downloaded last version and tried disabling ANSEL
Got the error message above.

**Comment by Ezeky3l** [comment]
same here.
Also crash when trying to change sharpenning value, maybe because this feature was removed from nvidia control panel.

**Comment by Sean-Paulk** [comment]
Ironically, I too wanted to disable Ansel and got the same problem. Reverted to an older driver that predates the newest version, 461.09, and the problem still persists.

**Comment by ShingenPizza** [comment]
I've got the same issue with 511.23 drivers.
Luckily setting NVIDIA Predefined Ansel Usage to ANSEL_ALLOW_DISALLOWED seems to have effectively disabled Ansel in a game where it caused issues, but i'd still prefer to disable it completely.
