### ISSUE TITLE
More settings from the control panel

### ISSUE THREAD

**Issue by tharos96** [Orbmu2k/nvidiaProfileInspector#88]
With the recent departure of non-dch drivers and thus the necessity to use the microsoft store control panel, would it be possible to enhance the profile inspector to substitute the control panel by adding settings as digital vibrance, scaling etc.?

**Comment by OnlyJiBiR** [comment]
These options and more can be changed through the registry some of the settings will be tied to your monitor.
what I suggest is to make a batch script with the settings that you gonna export from the registry and use that bat every time you install a new driver and you will not need the Nvidia cp anymore. << that's what I'm doing for the past 2 yrs I use my own bat script to set up everything from striping the driver to configuring every setting in Nvidia cp, enabling MSI mode & set the affinity for my GPU, Importing Nvidia Profile Inspector Settings & My CRU Settings, download & install Nvidia cp without the windows store.
so literally I don't do anything each time I install a new driver I just run any game and play 😄

I will try to make a guide going through everything I talked about when I have spare time.

**Comment by tharos96** [comment]
That sounds incredibly conventient. How do you account for newly added settings such as the new shader cache size option?

**Comment by Atlas1394** [comment]
> I will try to make a guide going through everything I talked about when I have spare time
I would be interested too!

**Comment by OnlyJiBiR** [comment]
> That sounds incredibly conventient. How do you account for newly added settings such as the new shader cache size option?

you can control the shader cache size through Nvidia Profile Inspector but you need to enter the value manually I will make it easy for you just follow my instructions:

1- Open NVidia Profile Inspector
2- Go 2 Shader disk cache maximum size
3- Enter the desired value manually and press apply
0x00000000 = Off
0x00000080 = 128MB
0x00000100 = 256MB
0x00000200 = 512MB
0x00000400 = 1GB
0x00001400 = 5GB
0x00002800 = 10GB
0x00019000 = 100GB
0xFFFFFFFF   = Unlimited
you can also add more options like 2GB the value for it should be = 0x00000800 

hope you find this helpful

**Comment by tharos96** [comment]
Nice, I'd be interested in how you find the respective keys in the registry and include them in your batch script when there are new settings. 
Also, would you mind sharing your scripts?

**Comment by OnlyJiBiR** [comment]
> Nice, I'd be interested in how you find the respective keys in the registry and include them in your batch script when there are new settings. Also, would you mind sharing your scripts?

you can monitor and track registry changes by using RegFromApp or something more advanced like Process Monitor or you can do it manually.
for the shader cache size values it's really simple if the option exists in the control panel & Nvidia profile inspector you just go through every setting that option has in the control panel and get each value for that option from Nvidia profile inspector because Nvidia profile inspector sometimes doesn't show you all the settings for a specific option so to get around this you need to get & enter the values manually.
about sharing my bat script I would love to share it but I need to edit some stuff to make it work without a hassle with others because the script was made for personal use but I can make it work however settings that gonna be tied to your display you will need to export the registry keys/values for it & insert them in the bat script.
finally, you can see the use of the script in this video + at the end of the video I explained how I got the values for the shader cache size & a brief explanation for RegFromApp.

https://www.youtube.com/watch?v=Aj7kSh2zE7Q

when I finish editing the bat script I will send you the link to test it.

**Comment by S0L1DSN4K3-96** [comment]
> > Nice, I'd be interested in how you find the respective keys in the registry and include them in your batch script when there are new settings. Also, would you mind sharing your scripts?
> 
> you can monitor and track registry changes by using RegFromApp or something more advanced like Process Monitor or you can do it manually. for the shader cache size values it's really simple if the option exists in the control panel & Nvidia profile inspector you just go through every setting that option has in the control panel and get each value for that option from Nvidia profile inspector because Nvidia profile inspector sometimes doesn't show you all the settings for a specific option so to get around this you need to get & enter the values manually. about sharing my bat script I would love to share it but I need to edit some stuff to make it work without a hassle with others because the script was made for personal use but I can make it work however settings that gonna be tied to your display you will need to export the registry keys/values for it & insert them in the bat script. finally, you can see the use of the script in this video + at the end of the video I explained how I got the values for the shader cache size & a brief explanation for RegFromApp.
> 
> https://www.youtube.com/watch?v=Aj7kSh2zE7Q
> 
> when I finish editing the bat script I will send you the link to test it.

I noticed that shadowplay worked after the script finished installing the driver is shadowplay stripped form gfe or does the script configure gfe during the install ?

**Comment by OnlyJiBiR** [comment]
Yes, I use a modified version of ShadowPlay fully stripped from GFE & other dependencies
Performance-wise there's no notable difference I modify it because I really despise Nvidia's telemetry.

**Comment by Anonanon** [comment]
> Yes, I use a modified version of ShadowPlay fully stripped from GFE & other dependencies Performance-wise there's no notable difference I modify it because I really despise Nvidia's telemetry.
Any chance you can share or point to a direction? All I have is classic GFE 2.11.

**Comment by OnlyJiBiR** [comment]
> > Yes, I use a modified version of ShadowPlay fully stripped from GFE & other dependencies Performance-wise there's no notable difference I modify it because I really despise Nvidia's telemetry.
> 
> Any chance you can share or point to a direction? All I have is classic GFE 2.11.

Unfortunately there is no direction to point at. i did the modification myself and with a lot of trials and errors for two weeks i figure out how to remove almost all the dependencies so shadowplay can run freely from GFE. the only thing that a found here in github is a way to bypass the login requirement for GFE.


  https://github.com/Moyster/BaiGfe/issues/28
  This can give you a hint of the kind of modification you're going to do.

Good luck.
