### ISSUE TITLE
use nvidia setting option in adjust desktop color settings

### ISSUE THREAD

**Issue by Damthe** [Orbmu2k/nvidiaProfileInspector#89]
![image](https://user-images.githubusercontent.com/21695940/141677467-0394c865-7f2e-4ea0-a243-3cd08686c612.png)

is there a corresponding option nvidiaProfileInspector for this one. this option is missing on newer drivers. but i need the option to fix the gamma bug in cs:go.

**Comment by Orbmu2k** [comment]
first of all, this tool is all abaout the game profiles inside the driver, not a controlpanel replacement ;-)

for me this settings are still there in recent drivers

![grafik](https://user-images.githubusercontent.com/18091040/141678163-8206df06-1150-490a-a503-db0679bcac59.png)
