### ISSUE TITLE
May need a way to simply type in the local file address of a game.

### ISSUE THREAD

**Issue by KirkH420** [Orbmu2k/nvidiaProfileInspector#90]
Hello,
First I just wanna say thank you for the great program. I'm not here complaining, but if possible I'd like to make a suggestion.

Summary:
The way you currently have Profile Inspector built, it has an open file dialogue for selecting a game for which the user wants to create a profile. It may improve Profile Inspector to allow the user to manually enter a game executable's location into a textbox.

The Open File Dialogue method isn't going to work for a game like Halo Infinite, currently available on the Microsoft Store. (I am not aware of how the Steam version works) The bulk of the game install appears to be some kind of Image file with no file extension. I believe Windows creates a small non-writeable directory where "Haloinfinite.exe" can be seen, and it will have no UAC permissions for the user. Also, Take Ownership methods do not work. Any changes to UAC will not be accepted, even if they're forced with PowerShell or something. (unless there are methods I'm not aware of)

Profile Inspector - If the user tries to use the Open File Dialogue, to select the game executable, they will be given an Access Denied messagebox.

I don't believe that Profile Inspector needs to write to the executable, that wouldn't make a lot of sense.
I think Profile Inspector only needs to know where the executable is.... 

Possibly if the GUI had a textbox for manually entering a game's location, then this problem could be circumvented?
I'm not sure on that... just a bit of a guess.

Anyway, Microsoft will probably release more games this way.
As far as I can tell, there is currently no way to configure Profile Inspector for a game that has the directory permissions locked in this way.

![Profile-Inspector-issue1](https://user-images.githubusercontent.com/29521840/143722511-5c5bf9a2-b231-4a16-b345-4264cb7a2a75.png)
![Profile-Inspector-issue2](https://user-images.githubusercontent.com/29521840/143722512-736259b4-a664-46f0-81d7-522ab592de82.png)

**Comment by Orbmu2k** [comment]
its a edge case for sure, but you can workaround it :)

you could create/copy any file and rename it to the same name and just choose it as placeholder or you export the profile as NIP and edit the NIP (just xml), add the application there and reimport ;-)
