### ISSUE TITLE
Download link for nvidia inspector standalone

### ISSUE THREAD

**Issue by Rexter2000** [Orbmu2k/nvidiaProfileInspector#95]
Been trying to locate a direct link for nvidia inspector standalone file.  When i download the nvidia profile inspector.zip there is no standalone nvidia inspector file in it.  i was assuming there would be an nvidia profile inspector file and a nvidia inspector standalone file, but i was mistaken.  Can you provide a link to download the nvidia inspector standalone file please?

Thanks,

Rex

**Comment by Hrxn** [comment]
Did you try this?
https://github.com/Orbmu2k/nvidiaProfileInspector/releases/latest

**Comment by Rexter2000** [comment]
Yes, no nvidia inspector.exe in it, I was assuming there would be a standalone file in the zip.
***@***.***
The only exe is the nvidiaprofileinspector which is for gaming profiles.

I am looking for the nvidiainspector.exe for being able to adjust power, memory, set fan speed, etc… on each GPU.
***@***.***

Can you send me a link to NVIDIA Inspector 1.9.7.3 or newer?

Thanks,

Rexter2000

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Orbmu2k** [comment]
you can download the latest version here

http://download.orbmu2k.de/files/nvidiaInspector.zip

**Comment by Rexter2000** [comment]
Thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brian6932** [comment]
@Orbmu2k can you fix the cert? 
![image](https://user-images.githubusercontent.com/18603393/234757498-b2be5462-9567-4d3d-b258-8d166ba6dd65.png)

**Comment by Orbmu2k** [comment]
> @Orbmu2k can you fix the cert? 

fixed :)
